package io.stride.spikes

import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.floor
import kotlin.math.hypot
import kotlin.math.min
import kotlin.math.sin

/**
 * Where the running track *is*: the ground plane, the perspective divide, and the fit onto whatever
 * box it has been given. Separate from [TrackFloorView], which decides what colour it all is.
 *
 * ### The ground plane
 *
 * A centreline ellipse is laid out in a normalised ground space whose short radius is 1 and whose
 * long radius is [groundRx]. The lane is generated by offsetting that centreline along its own
 * normal by a *constant* [laneHalf], so the track is one width the whole way round before
 * perspective touches it.
 *
 * That constant-width offset is the part the first version of this surface got wrong. Scaling the
 * whole ellipse down to make an inner edge produces a lane as wide as the radius difference on the
 * long axis and a sliver of that on the short one — a shape that pinches at the ends and balloons
 * at the sides, which is why it never read as a track.
 *
 * ### Travel is a distance, not an angle
 *
 * The lap position this surface is handed is a fraction of the lap's *length* — [LapTracker]
 * divides the machine's own distance register by the lap's length and hands over the remainder. So
 * `u` is arc length, and it has to be turned into an angle before the ellipse can be asked
 * anything. Feeding it straight in as the angle is the mistake this class used to make, and on an
 * ellipse this eccentric it is not a rounding error: a degree of angle is worth about two and a
 * half times as much ground on the straights as it is round the ends, so a rider running at a
 * steady pace watched their marker crawl along the near straight and then whip round the bend, and
 * the completed band was out by up to 3% of a lap in between the four extremes. [buildArcTable]
 * measures the centreline once per fit and inverts it, so equal steps in `u` are equal steps of
 * ground — which is also what makes the centre-line dashes come out evenly spaced.
 *
 * ### The camera
 *
 * Every ground point is divided by `1 - k * depth`, with depth running -1 at the far side to +1 at
 * the near one. x and y go through the same divide, so the near straight spreads wide and low while
 * the far one compresses toward the horizon, and the lane's *apparent* width varies for the one
 * honest reason: distance.
 *
 * ### Filling the box
 *
 * Nothing is a fraction of the view. [fit] solves the ground aspect so the projected outline has
 * the aspect of the box, then scales and centres it to fill that box exactly — so the same track
 * fills a short wide strip or the whole middle of the console without being redrawn by hand.
 */
class TrackGeometry(
    private val perspectiveK: Float = DEFAULT_PERSPECTIVE_K,
    private val laneHalf: Float = DEFAULT_LANE_HALF,
    private val samples: Int = DEFAULT_SAMPLES,
) {

    companion object {
        /**
         * A ground sample at depth `gy` is scaled by `1 / (1 - k * gy)`, making the near edge about
         * twice the far one. Higher reads as a lower camera; past roughly 0.45 the near straight
         * swings so wide it overruns the infield.
         */
        const val DEFAULT_PERSPECTIVE_K = 0.30f

        /** Lane half-width in ground units, where the ground ellipse's short radius is 1. */
        const val DEFAULT_LANE_HALF = 0.132f

        /** Samples around a lap when measuring. 288 is smooth at console width. */
        const val DEFAULT_SAMPLES = 288

        /**
         * The start line sits at the left extreme, and travel runs left -> near -> right -> far:
         * anticlockwise on screen, which puts the runner coming toward the rider along the near
         * straight exactly as they would on a real track.
         */
        const val START_ANGLE = PI.toFloat()

        /**
         * Proportions of the marker standing on the track, as multiples of the local lane width.
         *
         * They live here rather than with the painting because the marker has to be *fitted*, not
         * just drawn: it stands up out of the lane, so the box has to hold the lane and the marker
         * together. [TrackFloorView] draws from these same numbers so the two cannot drift.
         */
        const val PIN_SCALE = 1.15f
        const val PIN_HALF_WIDTH = 0.30f
        const val PIN_HEAD_OFFSET = 0.64f
        const val PIN_HEAD_RADIUS = 0.34f
        const val PIN_SHADOW_DROP = 0.10f

        /** How far the marker reaches above, below and either side of its point on the lane. */
        private const val MARKER_RISE = PIN_SCALE * (PIN_HEAD_OFFSET + PIN_HEAD_RADIUS)
        private const val MARKER_DROP = PIN_SCALE * PIN_SHADOW_DROP
        private const val MARKER_HALF_WIDTH = PIN_SCALE * PIN_HEAD_RADIUS

        private const val TAU = (2.0 * PI).toFloat()

        /** Steps used to measure the centreline before inverting it. */
        private const val ARC_SAMPLES = 2048

        /** Entries in the inverted distance -> angle table, which is interpolated between. */
        private const val ARC_TABLE = 512

        /** Passing anything outside this to [fit] means the ground ellipse would degenerate. */
        private const val MIN_GROUND_RX = 0.85f
        private const val MAX_GROUND_RX = 6f
    }

    /** Result of the last [project] call. Held in fields so a hot loop allocates nothing. */
    var x: Float = 0f
        private set
    var y: Float = 0f
        private set

    /**
     * The same point before the perspective divide, in ground units.
     *
     * Exposed because it is the only place the *real* track can be measured: screen distance is
     * perspective-weighted by construction, so nothing drawn can tell you whether two steps of
     * travel covered the same amount of ground. The arc-length parameterisation is checked against
     * these.
     */
    var groundX: Float = 0f
        private set
    var groundY: Float = 0f
        private set

    /**
     * Long radius of the ground ellipse, the short one being 1.
     *
     * Assigning it rebuilds the arc-length table, because that table is a measurement *of* this
     * ellipse and a stale one would put every travel fraction on the shape from the previous
     * solve. The solve in [solveGroundRx] assigns this several times, so the rebuild lives here
     * rather than at the call sites, where it would be one more thing to remember.
     */
    var groundRx: Float = 2.4f
        private set(value) {
            field = value
            buildArcTable()
        }
    var scale: Float = 1f
        private set
    var originX: Float = 0f
        private set
    var originY: Float = 0f
        private set

    /** Bounds of the hole in the middle, which is the only space the labels can safely have. */
    var infieldCenterX: Float = 0f
        private set
    var infieldCenterY: Float = 0f
        private set
    var infieldWidth: Float = 0f
        private set
    var infieldHeight: Float = 0f
        private set

    /** Top and bottom of the outer edge, for shaders that run with the depth of the floor. */
    var outerTop: Float = 0f
        private set
    var outerBottom: Float = 0f
        private set

    /** False until [fit] has been given a usable box. Nothing else is meaningful before then. */
    var ready: Boolean = false
        private set

    // Cumulative centreline length by angle, and its inverse: the fraction of the way round the
    // ellipse at each equal step of distance. Both are rebuilt by [buildArcTable] whenever the
    // ellipse changes, and only read after that, so a frame allocates nothing walking them.
    private val cumulative = FloatArray(ARC_SAMPLES + 1)
    private val phaseAt = FloatArray(ARC_TABLE + 1)

    // Scratch for the measuring pass. Lane bounds drive the shaders; the union of lane and marker
    // is what actually has to fit the box.
    private var laneMinY = 0f
    private var laneMaxY = 0f
    private var unionMinX = 0f
    private var unionMaxX = 0f
    private var unionMinY = 0f
    private var unionMaxY = 0f

    init {
        // The property initialiser above does not run the setter, so the default ellipse would
        // otherwise have an all-zero table until the first fit assigned a new radius.
        buildArcTable()
    }

    /**
     * Lay the track into a [width] x [height] box, inset by [padX] / [padY], and measure everything
     * that depends on that box. Returns false — and leaves [ready] false — for a box with no room.
     */
    fun fit(width: Float, height: Float, padX: Float, padY: Float): Boolean {
        ready = false
        val boxW = width - 2f * padX
        val boxH = height - 2f * padY
        if (boxW <= 0f || boxH <= 0f) return false

        // The solve and the measuring pass both run through [project], so the transform has to be
        // the identity while they do, or they measure the box from last time.
        scale = 1f
        originX = 0f
        originY = 0f
        groundRx = solveGroundRx(boxW / boxH)

        // Exact rather than iterative: the projection is homogeneous in the scale factor, so
        // measuring at scale 1 and then scaling and translating lands the shape on the box.
        measure(samples)
        val spanX = (unionMaxX - unionMinX).coerceAtLeast(0.0001f)
        val spanY = (unionMaxY - unionMinY).coerceAtLeast(0.0001f)
        scale = min(boxW / spanX, boxH / spanY)
        originX = width * 0.5f - (unionMinX + unionMaxX) * 0.5f * scale
        originY = height * 0.5f - (unionMinY + unionMaxY) * 0.5f * scale
        outerTop = laneMinY * scale + originY
        outerBottom = laneMaxY * scale + originY

        var innerMinX = Float.MAX_VALUE
        var innerMaxX = -Float.MAX_VALUE
        var innerMinY = Float.MAX_VALUE
        var innerMaxY = -Float.MAX_VALUE
        for (i in 0..samples) {
            project(i.toFloat() / samples, -1f)
            if (x < innerMinX) innerMinX = x
            if (x > innerMaxX) innerMaxX = x
            if (y < innerMinY) innerMinY = y
            if (y > innerMaxY) innerMaxY = y
        }
        infieldCenterX = (innerMinX + innerMaxX) * 0.5f
        infieldCenterY = (innerMinY + innerMaxY) * 0.5f
        infieldWidth = innerMaxX - innerMinX
        infieldHeight = innerMaxY - innerMinY

        ready = true
        return true
    }

    /**
     * Measure the lane outline and, with it, the envelope of the marker standing on the lane.
     *
     * Fitting the lane alone is not enough. The marker rises out of the track by more than a lane
     * width, so on the far straight — where the lane is highest on screen and the outline is
     * already touching the top of the box — the marker's head lands above the top edge and the
     * window clips it, for about a sixth of every lap. What has to fit the box is everything that
     * gets drawn, and the marker scales with the lane, so it can be measured in the same pass.
     */
    private fun measure(count: Int) {
        laneMinY = Float.MAX_VALUE
        laneMaxY = -Float.MAX_VALUE
        unionMinX = Float.MAX_VALUE
        unionMaxX = -Float.MAX_VALUE
        unionMinY = Float.MAX_VALUE
        unionMaxY = -Float.MAX_VALUE
        for (i in 0..count) {
            val u = i.toFloat() / count
            project(u, 1f)
            val ox = x
            val oy = y
            project(u, -1f)
            val laneWidth = hypot(ox - x, oy - y)
            if (oy < laneMinY) laneMinY = oy
            if (oy > laneMaxY) laneMaxY = oy
            if (ox < unionMinX) unionMinX = ox
            if (ox > unionMaxX) unionMaxX = ox
            if (oy < unionMinY) unionMinY = oy
            if (oy > unionMaxY) unionMaxY = oy

            project(u, 0f)
            val halfWidth = laneWidth * MARKER_HALF_WIDTH
            if (x - halfWidth < unionMinX) unionMinX = x - halfWidth
            if (x + halfWidth > unionMaxX) unionMaxX = x + halfWidth
            if (y - laneWidth * MARKER_RISE < unionMinY) unionMinY = y - laneWidth * MARKER_RISE
            if (y + laneWidth * MARKER_DROP > unionMaxY) unionMaxY = y + laneWidth * MARKER_DROP
        }
    }

    /**
     * Project the lane point at travel fraction [u] from the start line, offset [side] across the
     * lane (-1 inner, 0 centreline, +1 outer), leaving the answer in [x] and [y].
     *
     * [u] is a fraction of the lap's *length*, not of its angle — see the class note. Values
     * outside 0..1 wrap, which is what lets the start/finish chequer be laid out across the line
     * rather than after it.
     */
    fun project(u: Float, side: Float) {
        val theta = START_ANGLE - phaseFor(u) * TAU
        val cosT = cos(theta)
        val sinT = sin(theta)

        // Outward normal of the ground ellipse (groundRx * cos, sin) is (cos, groundRx * sin).
        val nx = cosT
        val ny = groundRx * sinT
        val n = hypot(nx, ny).coerceAtLeast(0.0001f)

        val gx = groundRx * cosT + side * laneHalf * nx / n
        val gy = sinT + side * laneHalf * ny / n

        // The perspective divide. Depth cannot reach 1 / perspectiveK, so this cannot blow up.
        val s = 1f / (1f - perspectiveK * gy)
        groundX = gx
        groundY = gy
        x = gx * s * scale + originX
        y = gy * s * scale + originY
    }

    /**
     * Turn a fraction of the lap's length into a fraction of the way round the ellipse.
     *
     * A table lookup rather than an integral: inverting arc length has no closed form on an
     * ellipse, and this is called several times per drawn frame.
     */
    private fun phaseFor(u: Float): Float {
        val wrapped = u - floor(u)
        val pos = wrapped * ARC_TABLE
        val i = pos.toInt().coerceIn(0, ARC_TABLE - 1)
        return phaseAt[i] + (phaseAt[i + 1] - phaseAt[i]) * (pos - i)
    }

    /**
     * Measure the ground centreline at [ARC_SAMPLES] equal steps of angle, then read that mapping
     * backwards into [phaseAt] at equal steps of distance.
     *
     * Runs once per candidate [groundRx] during the solve and once for the answer — a few thousand
     * trig calls on a size change, and nothing at all per frame.
     */
    private fun buildArcTable() {
        var previousX = groundRx * cos(START_ANGLE)
        var previousY = sin(START_ANGLE)
        cumulative[0] = 0f
        for (i in 1..ARC_SAMPLES) {
            val theta = START_ANGLE - (i.toFloat() / ARC_SAMPLES) * TAU
            val cx = groundRx * cos(theta)
            val cy = sin(theta)
            cumulative[i] = cumulative[i - 1] + hypot(cx - previousX, cy - previousY)
            previousX = cx
            previousY = cy
        }
        val total = cumulative[ARC_SAMPLES]
        // A degenerate ellipse has no length to distribute; fall back to the raw angle rather than
        // dividing by nothing. [fit] refuses such a box anyway, so this is only ever a guard.
        if (!(total > 0f)) {
            for (j in 0..ARC_TABLE) phaseAt[j] = j.toFloat() / ARC_TABLE
            return
        }
        phaseAt[0] = 0f
        phaseAt[ARC_TABLE] = 1f
        var i = 0
        for (j in 1 until ARC_TABLE) {
            val want = total * j / ARC_TABLE
            while (i < ARC_SAMPLES - 1 && cumulative[i + 1] < want) i++
            val span = cumulative[i + 1] - cumulative[i]
            val within = if (span > 0f) (want - cumulative[i]) / span else 0f
            phaseAt[j] = (i + within) / ARC_SAMPLES
        }
    }

    /** Width of the lane on screen where the runner is standing at travel fraction [u]. */
    fun laneWidthAt(u: Float): Float {
        project(u, 1f)
        val ox = x
        val oy = y
        project(u, -1f)
        return hypot(ox - x, oy - y)
    }

    /**
     * The ground x radius whose *projected* outline has the aspect of the box being filled.
     *
     * There is no closed form — the lane's offset direction depends on the radius being solved for
     * — but projected width is very nearly linear in it, so scaling the guess by the aspect error
     * converges in a handful of passes.
     */
    private fun solveGroundRx(targetAspect: Float): Float {
        var rx = targetAspect.coerceIn(MIN_GROUND_RX, MAX_GROUND_RX)
        repeat(8) {
            groundRx = rx
            measure(72)
            val aspect = (unionMaxX - unionMinX) / (unionMaxY - unionMinY).coerceAtLeast(0.0001f)
            rx = (rx * targetAspect / aspect.coerceAtLeast(0.0001f)).coerceIn(MIN_GROUND_RX, MAX_GROUND_RX)
        }
        groundRx = rx
        return rx
    }
}
