package io.stride.spikes

import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.floor
import kotlin.math.hypot
import kotlin.math.min
import kotlin.math.sin

/**
 * Where the running track *is*: the ground plane and the fit onto whatever box it has been given.
 * Separate from [TrackFloorView], which decides what colour it all is.
 *
 * ### A straight-down view
 *
 * This used to be seen through a low, angled camera — a perspective divide that made the near
 * straight spread wide and the far one recede toward a horizon, the way a track looks from track
 * level. It was dropped for a plain overhead view, the way an actual track reads on a diagram or
 * from a blimp: every point on the ground plane is equally far from the viewer, so nothing about
 * depth is faked.
 *
 * That is not only a look. It is what makes the lane's cross-section — the segment from outer edge
 * to inner edge at a given point on the loop — come out *exactly* perpendicular to the direction of
 * travel everywhere around the lap, with the camera gone: the offset is built along the true
 * geometric normal of whichever piece of the shape a point falls on (see [project]), and a
 * perpendicular direction survives the uniform scale and translation in [fit] without being
 * sheared.
 *
 * ### The ground plane is a stadium, not an ellipse
 *
 * A running track is two straights joined by two semicircular turns — a "stadium" or discorectangle
 * — not a smooth oval, and drawn from directly overhead that shape difference stops being something
 * perspective could paper over. The centreline is laid out in a normalised ground space whose turn
 * radius is 1 and whose straight length is [straightLen]: the bottom straight runs from
 * `(-straightLen/2, 1)` to `(straightLen/2, 1)`, the top mirrors it at `y = -1`, and a semicircle of
 * radius 1 joins each pair of ends. The lane is generated by offsetting that centreline along its
 * own normal by a *constant* [laneHalf] — outward along the straight's own perpendicular on a
 * straight, outward along the radius on a turn — so the track is one width the whole way round.
 *
 * That constant-width offset is the part the first version of this surface got wrong, back when the
 * shape was still an ellipse. Scaling the whole outline down to make an inner edge produces a lane
 * as wide as the radius difference on the straights and a sliver of that on the turns — a shape that
 * pinches at the ends and balloons at the sides, which is why it never read as a track.
 *
 * ### Travel is a distance, not an angle
 *
 * The lap position this surface is handed is a fraction of the lap's *length* — [LapTracker]
 * divides the machine's own distance register by the lap's length and hands over the remainder. On
 * a stadium this is exact and closed-form rather than a measured table: a straight is already
 * parametrised by distance (it is just its own x coordinate), and arc length along a circle of
 * radius 1 *is* the angle swept, so [project] converts `u` straight into ground coordinates with no
 * lookup and no approximation — unlike the ellipse this shape replaced, which had no closed form and
 * needed a measured, interpolated table (see git history). Equal steps in `u` are exactly equal
 * steps of ground, which is what keeps the centre-line dashes evenly spaced and the marker moving at
 * a constant pace for a constant one.
 *
 * ### Filling the box
 *
 * Nothing is a fraction of the view. [fit] solves [straightLen] so the projected outline has the
 * aspect of the box, then scales and centres it to fill that box exactly — so the same track fills a
 * short wide strip or the whole middle of the console without being redrawn by hand.
 */
class TrackGeometry(
    private val laneHalf: Float = DEFAULT_LANE_HALF,
    private val samples: Int = DEFAULT_SAMPLES,
) {

    companion object {
        /** Lane half-width in ground units, where a turn's own radius is 1. */
        const val DEFAULT_LANE_HALF = 0.132f

        /** Samples around a lap when measuring. 288 is smooth at console width. */
        const val DEFAULT_SAMPLES = 288

        /**
         * Proportions of the marker standing on the track, as multiples of the local lane width.
         *
         * They live here rather than with the painting because the marker has to be *fitted*, not
         * just drawn: it reaches above its point on the lane like a map pin, so the box has to hold
         * the lane and the marker together. [TrackFloorView] draws from these same numbers so the
         * two cannot drift.
         */
        const val PIN_SCALE = 1.15f
        const val PIN_HALF_WIDTH = 0.30f
        const val PIN_HEAD_OFFSET = 0.64f
        const val PIN_HEAD_RADIUS = 0.34f
        const val PIN_SHADOW_DROP = 0.10f

        /** How far the marker reaches above, below and either side of its point on the lane. */
        private const val MARKER_RISE = PIN_SCALE * (PIN_HEAD_OFFSET + PIN_HEAD_RADIUS)
        private const val MARKER_DROP = PIN_SCALE * PIN_SHADOW_DROP
        private const val MARKER_HALF_WIDTH = PIN_SCALE * PIN_HEAD_RADIUS

        private const val HALF_PI = (PI / 2.0).toFloat()

        /** Passing anything outside this to [fit] means the stadium would degenerate. */
        private const val MIN_STRAIGHT_LEN = 0f
        private const val MAX_STRAIGHT_LEN = 12f
    }

    /** Result of the last [project] call. Held in fields so a hot loop allocates nothing. */
    var x: Float = 0f
        private set
    var y: Float = 0f
        private set

    /**
     * The same point in ground units — before [scale] and the box's own origin are applied, which
     * differ from one fitted box to the next.
     *
     * With no camera, this is [x]/[y] up to that one affine transform, but it is still the right
     * thing to measure travel against: a screen-pixel distance is a fact about the box a given fit
     * happened to be given, and the arc-length parameterisation has to hold regardless of box size,
     * so it is checked against these instead.
     */
    var groundX: Float = 0f
        private set
    var groundY: Float = 0f
        private set

    /**
     * Length of each straight in ground units, where a turn's own radius is fixed at 1.
     *
     * The one free parameter [fit] solves for: everything else about the stadium's proportions
     * follows from it and the fixed turn radius.
     */
    var straightLen: Float = 2.4f
        private set
    var scale: Float = 1f
        private set
    var originX: Float = 0f
        private set
    var originY: Float = 0f
        private set

    /** Bounds of the hole in the middle, which is the only space the labels can safely have. */
    var infieldCenterX: Float = 0f
        private set
    var infieldCenterY: Float = 0f
        private set
    var infieldWidth: Float = 0f
        private set
    var infieldHeight: Float = 0f
        private set

    /** Top and bottom of the outer edge, for shaders that run with the depth of the floor. */
    var outerTop: Float = 0f
        private set
    var outerBottom: Float = 0f
        private set

    /** False until [fit] has been given a usable box. Nothing else is meaningful before then. */
    var ready: Boolean = false
        private set

    // Scratch for the measuring pass. Lane bounds drive the shaders; the union of lane and marker
    // is what actually has to fit the box.
    private var laneMinY = 0f
    private var laneMaxY = 0f
    private var unionMinX = 0f
    private var unionMaxX = 0f
    private var unionMinY = 0f
    private var unionMaxY = 0f

    /**
     * Lay the track into a [width] x [height] box, inset by [padX] / [padY], and measure everything
     * that depends on that box. Returns false — and leaves [ready] false — for a box with no room.
     */
    fun fit(width: Float, height: Float, padX: Float, padY: Float): Boolean {
        ready = false
        val boxW = width - 2f * padX
        val boxH = height - 2f * padY
        if (boxW <= 0f || boxH <= 0f) return false

        // The solve and the measuring pass both run through [project], so the transform has to be
        // the identity while they do, or they measure the box from last time.
        scale = 1f
        originX = 0f
        originY = 0f
        straightLen = solveStraightLen(boxW / boxH)

        // Exact rather than iterative: the projection is homogeneous in the scale factor, so
        // measuring at scale 1 and then scaling and translating lands the shape on the box.
        measure(samples)
        val spanX = (unionMaxX - unionMinX).coerceAtLeast(0.0001f)
        val spanY = (unionMaxY - unionMinY).coerceAtLeast(0.0001f)
        scale = min(boxW / spanX, boxH / spanY)
        originX = width * 0.5f - (unionMinX + unionMaxX) * 0.5f * scale
        originY = height * 0.5f - (unionMinY + unionMaxY) * 0.5f * scale
        outerTop = laneMinY * scale + originY
        outerBottom = laneMaxY * scale + originY

        var innerMinX = Float.MAX_VALUE
        var innerMaxX = -Float.MAX_VALUE
        var innerMinY = Float.MAX_VALUE
        var innerMaxY = -Float.MAX_VALUE
        for (i in 0..samples) {
            project(i.toFloat() / samples, -1f)
            if (x < innerMinX) innerMinX = x
            if (x > innerMaxX) innerMaxX = x
            if (y < innerMinY) innerMinY = y
            if (y > innerMaxY) innerMaxY = y
        }
        infieldCenterX = (innerMinX + innerMaxX) * 0.5f
        infieldCenterY = (innerMinY + innerMaxY) * 0.5f
        infieldWidth = innerMaxX - innerMinX
        infieldHeight = innerMaxY - innerMinY

        ready = true
        return true
    }

    /**
     * Measure the lane outline and, with it, the envelope of the marker standing on the lane.
     *
     * Fitting the lane alone is not enough. The marker rises above the track by more than a lane
     * width, so at the top of the loop — where the outline is already touching the top of the box —
     * the marker's head lands above the top edge and the window clips it, for about a sixth of
     * every lap. What has to fit the box is everything that gets drawn, and the marker scales with
     * the lane, so it can be measured in the same pass.
     */
    private fun measure(count: Int) {
        laneMinY = Float.MAX_VALUE
        laneMaxY = -Float.MAX_VALUE
        unionMinX = Float.MAX_VALUE
        unionMaxX = -Float.MAX_VALUE
        unionMinY = Float.MAX_VALUE
        unionMaxY = -Float.MAX_VALUE
        for (i in 0..count) {
            val u = i.toFloat() / count
            project(u, 1f)
            val ox = x
            val oy = y
            project(u, -1f)
            val laneWidth = hypot(ox - x, oy - y)
            if (oy < laneMinY) laneMinY = oy
            if (oy > laneMaxY) laneMaxY = oy
            if (ox < unionMinX) unionMinX = ox
            if (ox > unionMaxX) unionMaxX = ox
            if (oy < unionMinY) unionMinY = oy
            if (oy > unionMaxY) unionMaxY = oy

            project(u, 0f)
            val halfWidth = laneWidth * MARKER_HALF_WIDTH
            if (x - halfWidth < unionMinX) unionMinX = x - halfWidth
            if (x + halfWidth > unionMaxX) unionMaxX = x + halfWidth
            if (y - laneWidth * MARKER_RISE < unionMinY) unionMinY = y - laneWidth * MARKER_RISE
            if (y + laneWidth * MARKER_DROP > unionMaxY) unionMaxY = y + laneWidth * MARKER_DROP
        }
    }

    /**
     * Project the lane point at travel fraction [u] from the start line, offset [side] across the
     * lane (-1 inner, 0 centreline, +1 outer), leaving the answer in [x] and [y].
     *
     * [u] is a fraction of the lap's *length*, not of its angle. The start line sits at the midpoint
     * of the bottom straight — `(0, 1)` — matching where a real track's start/finish stripe sits,
     * on a straight rather than mid-turn, and travel runs right along the bottom, up through the
     * right-hand turn, left along the top, down through the left-hand turn, and back: anticlockwise
     * on screen, the direction a track diagram is usually drawn. Values outside 0..1 wrap, which is
     * what lets the start/finish chequer be laid out across the line rather than after it.
     *
     * The five pieces below are walked in that order, each one picked up exactly where the last one
     * left off (a straight's own length is its arc length; a turn's radius is 1, so its arc length
     * *is* the angle it sweeps) — there is nothing to invert and nothing to measure, unlike the
     * ellipse this shape replaced.
     */
    fun project(u: Float, side: Float) {
        val half = straightLen * 0.5f
        val perimeter = 2f * straightLen + 2f * PI.toFloat()
        var s = (u - floor(u)) * perimeter

        val turnBoundary = half + PI.toFloat()
        val farStraightEnd = turnBoundary + straightLen
        val farTurnBoundary = farStraightEnd + PI.toFloat()

        val gx: Float
        val gy: Float
        when {
            // Bottom straight, right half: start line to the right-hand turn.
            s < half -> {
                gx = s
                gy = 1f + side * laneHalf
            }
            // Right-hand turn: a full semicircle around (half, 0), swept clockwise in ground space
            // from the bottom straight's end to the top straight's end.
            s < turnBoundary -> {
                val angle = HALF_PI - (s - half)
                val r = 1f + side * laneHalf
                gx = half + r * cos(angle)
                gy = r * sin(angle)
            }
            // Top straight, right to left.
            s < farStraightEnd -> {
                gx = half - (s - turnBoundary)
                gy = -1f - side * laneHalf
            }
            // Left-hand turn: the other semicircle, around (-half, 0).
            s < farTurnBoundary -> {
                val angle = -HALF_PI - (s - farStraightEnd)
                val r = 1f + side * laneHalf
                gx = -half + r * cos(angle)
                gy = r * sin(angle)
            }
            // Bottom straight, left half: back to the start line.
            else -> {
                gx = -half + (s - farTurnBoundary)
                gy = 1f + side * laneHalf
            }
        }

        // Straight overhead: scale and translate into the box, nothing else. The offset above is
        // built along each piece's own true geometric normal — perpendicular to a straight, radial
        // on a turn — so it stays perpendicular to the direction of travel everywhere; the uniform
        // scale here cannot shear it off-square the way a depth-dependent camera divide used to.
        groundX = gx
        groundY = gy
        x = gx * scale + originX
        y = gy * scale + originY
    }

    /** Width of the lane on screen where the runner is standing at travel fraction [u]. */
    fun laneWidthAt(u: Float): Float {
        project(u, 1f)
        val ox = x
        val oy = y
        project(u, -1f)
        return hypot(ox - x, oy - y)
    }

    /**
     * The straight length whose *projected* outline has the aspect of the box being filled.
     *
     * There is no closed form — the marker's envelope, which also has to fit, depends on the shape
     * being solved for — but the projected aspect only ever grows as the straight lengthens (a
     * longer straight makes the shape wider and never shorter), so bisection finds it reliably
     * regardless of how flat or steep that growth is at any particular length.
     *
     * A multiplicative update — scale the guess by how wrong its aspect is — converges in a handful
     * of passes when the aspect is reasonably sensitive to the length, which it is almost everywhere
     * *except* right where a near-square box needs to land: the marker's fixed envelope dominates
     * the shape's own extent there, so the aspect barely moves per unit of length and that update
     * rule stalls for dozens of passes. Bisection's cost does not depend on how sensitive the
     * function is, only on how many times the interval halves, so it costs the same handful of
     * passes everywhere, including there.
     */
    private fun solveStraightLen(targetAspect: Float): Float {
        var lo = MIN_STRAIGHT_LEN
        var hi = MAX_STRAIGHT_LEN
        repeat(30) {
            val mid = (lo + hi) * 0.5f
            straightLen = mid
            measure(72)
            val aspect = (unionMaxX - unionMinX) / (unionMaxY - unionMinY).coerceAtLeast(0.0001f)
            if (aspect < targetAspect) lo = mid else hi = mid
        }
        straightLen = hi
        return hi
    }
}
